logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.hansjoerg.coloringbook: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require&reWriteBatchedInserts=true&prepareThreshold=0
    username: postgres.yqnawjlxlyuxhlymhnpv
    password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 686279034351-7h9igi1ef7ja11di7a2f1v8o20ip94lh.apps.googleusercontent.com
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  flyway:
    enabled: false # Disabled Flyway
    locations: classpath:db/migration
    baseline-on-migrate: true
  liquibase: # Liquibase configuration
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml # Path to your master changelog

app:
  swagger:
    password: ${SWAGGER_PWD}
  frontend:
    baseUrl: ${FRONTEND_URL}
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins:${FRONTEND_URL},http://localhost:8080,https://coloringbook-backend-ikyz.onrender.com
  oauth2:
    authorizedRedirectUris:
      - ${FRONTEND_URL}/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
